### PR TITLE
WIP Add support for downloading package file

### PR DESCRIPTION
**Pull request by hdep**
This PR add support for downloading deb or rpm file from a webserver and installed it.

This is usefull when you don't have a local deb or rpm repository available.

### CODE REVIEW

**Comment by hdep** [comment]
Hi @coreone are you interested for this PR ?

**Comment by coreone** [comment]
@hdep I like the idea of proxy and packaging changes.  However, I would like to see those two changes in 2 different PRs so we can segment out the changes.  A couple of other notes:

- Run `pre-commit` on the repo prior to commits (or as a git hook) to correct any linting issues
- If you are going to add proxy support, you should probably fully support the proxy (optional username, password, and port as well)
  - `qualys_https_proxy=https://[<username>:<password>@]<host>[:<port>]`
- Put defaults for `$default_config_path` and `$package_filename` in hiera data (`RedHat-family.yaml`, etc.), not if/else statements.

**Comment by coreone** [comment]
Also, tests would need to be added for any changes.

**Comment by coreone** [comment]
@hdep note that another PR went in to add the proxy piece of this, so if you rebase your commit it should now only need to worry about adding the packaging piece now.

**Comment by coreone** [comment]
@hdep Our default branch has changed to `main` as well, and this PR has been updated to be based against that branch.  Please rebase on that branch to pick up recent changes.

**Comment by hdep** [comment]
Hello @coreone

Sorry i've been quite busy on other module maintenance;
I'll try to give some time. As i'm working on windows I'm not able to run pre-commit.  Has this is quite old I think I'll start again from scratch.

**Comment by coreone** [comment]
No worries. Was just on a sweep of old PRs. Thanks!

**Comment by hdep** [comment]
please see #24

**Pull request closed without merging**
